name: "PR-Sense"
description: "Instant bilingual TL;DR (German & English) plus breaking-change radar - pull request"
author: "disa87"

# keine Eingaben mehr nötig
inputs: {}

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "blue"
