name: "PR-Sense · Marketplace Hook"

on:
  marketplace_purchase:
    types: [purchased, changed]

permissions:
  contents: read            # reicht aus

jobs:
  update-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Patch plan in master-gist
        env:
          GIST_ID:     ${{ secrets.ORG_GIST_ID }}
          GIST_TOKEN:  ${{ secrets.ORG_GIST_TOKEN }}
          ACCOUNT_ID:  ${{ github.event.marketplace_purchase.account.id }}
          NEW_PLAN:    ${{ github.event.marketplace_purchase.plan.name }}
        shell: bash
        run: |
          set -e
          FILE="usage-${ACCOUNT_ID}.json"
          HDR=(-H "Authorization: Bearer $GIST_TOKEN" -H "Accept: application/vnd.github+json")
          
          # Gist lesen
          JSON=$(curl -s "${HDR[@]}" https://api.github.com/gists/$GIST_ID)
          CONTENT=$(echo "$JSON" | jq -r ".files[\"$FILE\"].content // \"{}\"")
          echo "$CONTENT" > tmp.json
          
          # Plan setzen (ohne Zähler zu verändern)
          jq ".plan=\"${NEW_PLAN,,}\"" tmp.json > new.json
          
          # Schreiben
          curl -s -X PATCH "${HDR[@]}" \
            -d "{\"files\": {\"$FILE\": {\"content\": $(jq -Rs . < new.json)}}}" \
            https://api.github.com/gists/$GIST_ID > /dev/null
          
          echo "Plan für Account $ACCOUNT_ID => $NEW_PLAN hinterlegt."
